version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu-bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: npm start